### ISSUE TITLE
Segmentation fault (core dumped) Linux Launcher Ubuntu Bionic 18.4 64 bit 

### ISSUE THREAD

**Issue by azispratama92** [duelists-unite/omega-releases#1]
Dear Developer, recently i tested the launcher on GNU/Linux 64 bit, it gave me 'Segmentation fault (core dumped)' error.

is there any specific dependency to be installed before running the file ? here is my inxi-F output

`System:    Host: Pratama Kernel: 5.2.0 x86_64 bits: 64 Desktop: Xfce 4.12.3
           Distro: Ubuntu 18.04.2 LTS
Machine:   Device: laptop System: LENOVO product: 20296 v: Lenovo IdeaPad S410p serial: N/A
           Mobo: LENOVO model: Lenovo IdeaPad S410p v: FAB3 serial: N/A
           UEFI [Legacy]: LENOVO v: 89CN32WW date: 11/22/2013
Battery    BAT0: charge: 7.0 Wh 23.8% condition: 29.4/31.7 Wh (93%)
CPU:       Dual core Intel Core i5-4200U (-MT-MCP-) cache: 3072 KB
           clock speeds: max: 2600 MHz 1: 1120 MHz 2: 1062 MHz 3: 1099 MHz
           4: 1104 MHz
Graphics:  Card: Intel Haswell-ULT Integrated Graphics Controller
           Display Server: x11 (X.Org 1.19.6 )
           drivers: modesetting (unloaded: fbdev,vesa)
           Resolution: 1366x768@60.01hz
           OpenGL: renderer: Mesa DRI Intel HD Graphics 4400 (HSW GT2)
           version: 4.5 Mesa 20.0.8`
![image](https://user-images.githubusercontent.com/17444955/104399597-f427db80-558b-11eb-92b1-52d188adbce7.png)

**Comment by azispratama92** [comment]
sorry, just read the rules, i'll closed this thread.

**Comment by shadowfox87** [comment]
Don't worry. You didn't break any rules. You need the latest Vulkan drivers.

Try this `sudo apt install mesa-vulkan-drivers mesa-vulkan-drivers:i386`

**Comment by azispratama92** [comment]
Thanks @shadowfox87 && @SamuelB-YGO for the quick response, 

i made a youtube video about omega launcher both native and wine (for windows launcher) in here: 
[https://youtu.be/A5Fr3qwkyVw](url)

Last night i was able to install the lastest proprietary nvidia driver for my Ubuntu. 

`Thu Jan 14 10:20:48 2021       
+------------------------------------------------------+                       
| NVIDIA-SMI 340.108    Driver Version: 340.108        |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GT 720M     Off  | 0000:04:00.0     N/A |                  N/A |
| N/A   39C    P8    N/A /  N/A |    200MiB /  2047MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+` 

The vulkan dependency is do the magic, i can run the game now, still can't open the main menu for some reason, i can only see my mouse cursors being changed into big blue delta. On the other hand i tested also the windows launcher via wine, the update and resource download run flawlessly, it still can't detect the native linux discord, so i can't test the online feature, and the mouse will stop working after move to another active window/ app in Linux.

**Comment by SamuelB-YGO** [comment]
@azispratama92  In order for the game to detect your discord you must have the actual .deb file build for Discord. Discord for Ubuntu tries to default to a .snap build. The game can not detect a discord.snap. In order to fix this  go to terminal and copy these commands:
cd snap (should open your snap directory)
sudo snap remove discord
 will look something like this:

$ sudo snap remove discord
[sudo] password for samuelb: (will ask for your password not mine)
discord removed

to add the deb file discord from terminal paste the commands:

$ wget -O discord.deb "https://discordapp.com/api/download?platform=linux&format=deb

then

$ sudo dpkg -i /path/to/discord.deb

then

open discord from your desktop (GUI)

**Comment by azispratama92** [comment]
@SamuelB-YGO my discord is already installed via officials *.deb Package, wine can run the windows-launcher, but can't detect the native linux discord binary, 

after installing the vulkan dependency, my linux launcher run, no segementation fault etc. But i can't got it work into main meno, only show up big delta mouse cursors, here is the screenshot: 
![image](https://user-images.githubusercontent.com/17444955/104542750-1b031200-565f-11eb-8fb2-8e1b512d7557.png)

as you can see, the main menu won't show up, i don't hear any game sound either, like in the windows-launcher with wine, 
btw are using debian ? what graphic card did u used to run this game?

**Comment by SamuelB-YGO** [comment]
Yeah, I am not a fan of the cursor either. It is part of the native GUI with Unity. I have tried to have it scaled down several times, but it seems it is impossible, but I will continue to work on it.

**Comment by SamuelB-YGO** [comment]
I use Ubuntu 20.04 (its basically GNU/DEB).  I actually use the built in Intel graphics card and I use the Intel V915 drivers.

**Comment by azispratama92** [comment]
Finally Fixed!!
![image](https://user-images.githubusercontent.com/17444955/104682538-de531b80-572f-11eb-89cf-502217bcf7d5.png)

what i did: 

1. add apt-repository, follow [this link](https://linoxide.com/linux-how-to/install-nvidia-drivers-ubuntu/) for further instruction
2. install mesa-vulkan-drivers
3. install the nvidia-driver using the gui-driver menu 
4. add execution access for the binary launcher `$ chmod +x,` don't use sudo here!
5. run the native linux discord app (via officials *.deb, don't install from snapcraft).
6. run the binary linux omega ygo via konsole, like this `./YGO\ Omega.x86_64 `

![image](https://user-images.githubusercontent.com/17444955/104682895-badca080-5730-11eb-9f29-f0679f8fbc1e.png) 

i'll close this thread now. Thanks a lot guys  @shadowfox87 && @SamuelB-YGO,
 finally i can play ranked tag game after 4 years hiatus :P
