### ISSUE TITLE
Android device can't update/download the games

### ISSUE THREAD

**Issue by hataian2003** [duelists-unite/omega-releases#12]
Hi, i'm using a Samsung Galaxy note 10. I downloaded the .apk file and installed it at 90%+ battery but i can't not update the client. There is a box appeared when open the app say "A new client update is needed" or something like that, but when i press the update button it just take me to the internet browser with the github link on the browser. Sorry for the bad english.

**Comment by HKunogi** [comment]
The first released version didnt contain the auto-updater on itself, so you need to download the newest apk on releases and then update your apk by installing it on top of it, from there on the game auto-update should download and prompt to install on top automatically.
