### ISSUE TITLE
Building a snap

### ISSUE THREAD

**Issue by Bios-Marcel** [duelists-unite/omega-releases#15]
Hey,

I am currently trying to build a snap, mainly because the source code doesn't seem to be available. However, I am running into an issue here. It seems the launcher attempts to save stuff to the current working directory.

It gives the following error:

```
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/mnt/data/code/omega-launcher' is denied.
```

It'd be nice if there was a command that could be used to specify a path. This would allow passing a snap-internal path, avoiding file system exposure.

EDIT:
I just noticed there's a discord dependency too, so I am assuming this will be the next step I'll fail at?
Could there potentially be a different way to do this? I heard this is mostly for preventing spam on the servers or something?

**Comment by HKunogi** [comment]
The updater always work on the directory it is placed into, but after it did what it needs to do, or before that, you can move it freely together with the stuff and it will work fine, it dont binds itself anywhere, it simply performs the desired tasks bound to where it is. The discord sdk is already bundled on the game that the updater downloads. If you using discord client you need to use the official discord install thingy provided by them, snaps seems to not be compatible with it.

**Comment by Bios-Marcel** [comment]
Yeah, I just realised that. Bad choices were made here imo, but whatever.
