### ISSUE TITLE
Error on executiomn

### ISSUE THREAD

**Issue by Fermich11** [duelists-unite/omega-releases#3]
I'm a little bit lost on how to install the game on Linux, I download the linux zip, and run the file on it, but every time it tries to open the game after download it fails, also caught my attention that the error mention win32: 
![image](https://user-images.githubusercontent.com/35929537/111858867-d23b3400-8901-11eb-889b-231f6d4f9a75.png)

**Comment by SamuelB-YGO** [comment]
Will never work running the Program as sudo root. Fist chmod OmegaUpdater.x86_64. (not as root) 

$ chmod OmegaUpdater.x86_64 -e 775

then just run the file as normal, again not as root, 

$ ./OmegaUpdater.x86_64

when it is finished it should try and launch Ygo_Omega.x86_66, but it will fail for the same reasons.

go back into the source folder of YHgo_Omega 
Ygo_Omega>$ chmod Ygo\ Omega.x86_64 -e 775

then launch the program from Terminal (again nmot as root or sudo)

$ ./Ygo\ Omega.x86_64.

We have a FAQ/Walkthru up on the DuelistsUnite forum that can walk you though installation and dependencies needed to run the program. We also have a dedicated Tech Support Channel on the Ygo Omega Discord channel. Should you have any mopre issues feel free to look us up on Discord.
